name: orca_clean
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - appdirs=1.4.4
  - astroid=2.5
  - audioread=2.1.9
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.4.13
  - certifi=2020.12.5
  - cffi=1.14.5
  - chardet=4.0.0
  - cloudpickle=1.6.0
  - cryptography=3.4.7
  - cudatoolkit=10.2.89
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask-core=2021.4.0
  - dbus=1.13.18
  - decorator=4.4.2
  - expat=2.3.0
  - ffmpeg=4.3
  - fontconfig=2.13.1
  - freetype=2.10.4
  - fsspec=0.9.0
  - gettext=0.19.8.1
  - glib=2.68.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=2.10
  - imageio=2.9.0
  - intel-openmp=2021.2.0
  - isort=5.8.0
  - joblib=1.0.1
  - jpeg=9b
  - kiwisolver=1.3.1
  - lame=3.100
  - lazy-object-proxy=1.6.0
  - lcms2=2.12
  - ld_impl_linux-64=2.33.1
  - libffi=3.3
  - libflac=1.3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.0
  - libllvm10=10.0.1
  - libogg=1.3.4
  - libopus=1.3.1
  - libpng=1.6.37
  - libprotobuf=3.16.0
  - librosa=0.8.0
  - libsndfile=1.0.31
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.1.0
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libuv=1.40.0
  - libvorbis=1.3.7
  - libxcb=1.14
  - libxml2=2.9.10
  - llvmlite=0.36.0
  - locket=0.2.1
  - lz4-c=1.9.3
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mccabe=0.6.1
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - ncurses=6.2
  - nettle=3.7.2
  - networkx=2.5.1
  - ninja=1.10.2
  - numba=0.53.1
  - numpy=1.20.1
  - numpy-base=1.20.1
  - olefile=0.46
  - openh264=2.1.0
  - openssl=1.1.1k
  - packaging=20.9
  - partd=1.2.0
  - pcre=8.44
  - pillow=8.2.0
  - pip=21.0.1
  - pooch=1.3.0
  - protobuf=3.16.0
  - pycparser=2.20
  - pylint=2.7.4
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pysocks=1.7.1
  - pysoundfile=0.10.3.post1
  - python=3.8.8
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytorch=1.8.1
  - pywavelets=1.1.1
  - pyyaml=5.4.1
  - qt=5.9.7
  - readline=8.1
  - requests=2.25.1
  - resampy=0.2.2
  - scikit-image=0.18.1
  - scikit-learn=0.24.1
  - scipy=1.6.2
  - setuptools=52.0.0
  - sip=4.19.13
  - six=1.15.0
  - sqlite=3.35.4
  - tensorboardx=2.2
  - threadpoolctl=2.1.0
  - tifffile=2020.10.1
  - tk=8.6.10
  - toml=0.10.2
  - toolz=0.11.1
  - torchvision=0.9.1
  - tornado=6.1
  - typing_extensions=3.7.4.3
  - urllib3=1.26.4
  - wheel=0.36.2
  - wrapt=1.12.1
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - opencv-python==4.5.2.52
